services:
  decoder:
    build:
      context: ./decoder
      dockerfile: Dockerfile
    environment:
      - DECODER_ID=0xdeadbeef
    volumes:
      - ./build_out:/build_out
      - ./decoder:/decoder
      - ./secrets:/secrets
