services:
  decoder:
    build:
      context: ./decoder
      dockerfile: Dockerfile
    environment:
      - DECODER_ID=0xdeadbeef
    volumes:
      - ./build_out:/out
      - ./decoder:/decoder
      - ./secrets/global.secrets:/global.secrets:ro
