[package]
name = "design_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", features = ["extra-traits", "full"] }
rand = "0.8.5"

[lib]
proc-macro = true
