[env]
BUILD_TYPE="release"

[tasks.buildall]
dependencies = [
  "decoder",
]

[tasks.decoder]
dependencies = ["decoder_elf", "decoder_bin"]


[tasks.decoder_elf_build]
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf", "--profile", "@@decode(BUILD_TYPE,release,release,debug,dev)"]

[tasks.decoder_bin]
dependencies = ["decoder_elf"]
script = [
  "arm-none-eabi-objcopy -O binary ${CARGO_TARGET_DIR}/thumbv7em-none-eabihf/${BUILD_TYPE}/decoder ${CARGO_TARGET_DIR}/thumbv7em-none-eabihf/${BUILD_TYPE}/decoder.bin --strip-unneeded",
  "cp ${CARGO_TARGET_DIR}/thumbv7em-none-eabihf/${BUILD_TYPE}/decoder.bin /out/max78000.bin"
]

[tasks.decoder_elf_copy]
command = "cp"
args = ["${CARGO_TARGET_DIR}/thumbv7em-none-eabihf/${BUILD_TYPE}/decoder", "/out/max78000.elf"]

[tasks.decoder_elf]
run_task = { name = ["decoder_elf_build", "decoder_elf_copy"] }

# [tasks.make_build]
# command = "mkdir"
# args = ["-p", "/out"]


# [tasks.cleanbin]
# script = [
#   "rm -rf build"
# ]

[tasks.all]
# dependencies = ["cleanbin", "buildall"]
dependencies = ["buildall"]
