[toolchain]
#channel = "nightly-2024-02-19"
# Latest nightly panics when building, chose a random nigthly that works (this is some 1.83.0 nightly)
channel = "nightly-2024-09-19"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "thumbv7em-none-eabihf" ]
profile = "minimal"
