[package]
name = "design_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
design_macros = { path = "../design_macros" }
max78000_hal = { path = "../max78000_hal" }
rand_core = { version = "0.6.4", default-features = false }
subtle = { version = "2.5", default-features = false }